# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmenGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_img', models.CharField(blank=True, help_text='Location Description', max_length=100, verbose_name='Name of Amenitie')),
                ('picture', models.ImageField(upload_to='building/NearbyAtraction/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('building',)},
        ),
        migrations.RemoveField(
            model_name='department',
            name='adress',
        ),
        migrations.AddField(
            model_name='nearbyatraction',
            name='picture',
            field=models.ImageField(default=None, upload_to='building/NearbyAtraction/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nearbyatraction',
            name='titulo_img',
            field=models.CharField(help_text='Location Description', max_length=100, verbose_name='Name of Amenitie'),
        ),
        migrations.AddField(
            model_name='departmengalery',
            name='departmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Department'),
        ),
    ]
