# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20160801_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmengalery',
            name='picture',
            field=models.ImageField(upload_to='building/Departments/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='number_of_apartment',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Apartment Number'),
            preserve_default=False,
        ),
    ]
